### ISSUE TITLE
Support batch transformations

### ISSUE THREAD

**Issue by isuruf** [zachjweiner/pycl-fft#2]
Currently FFTDim is set to the shape of the array which means batch FFTs cannot be done.

**Comment by zachjweiner** [comment]
The high-level interface definitely doesn't. But I think one can achieve batching with the `Transform` classes (at least, full generality is intended). IIUC, it's numberBatches and not FFTDim that specifies the batching?

**Comment by zachjweiner** [comment]
Indeed, the following batched, 1D C2C transform works:

```python
import numpy as np
import scipy.fft as spf
import pyopencl as cl
import pyopencl.array as cla
import pycl_fft as clf

ctx = cl.create_some_context()
queue = cl.CommandQueue(ctx)

shape = (32,)
dtype = np.dtype("complex128")
nbatch = 3

rng = np.random.default_rng(seed=979234)

x_h = rng.uniform(-1/2, 1/2, (nbatch,)+shape)
if dtype.kind == "c":
    x_h = x_h + 1j * rng.uniform(-1/2, 1/2, (nbatch,)+shape)
y_h = spf.fftn(x_h, s=shape)

x = cla.to_device(queue, x_h)
y = cla.empty_like(x)
transform = clf.vkfft.Transform(x.context, shape, x.dtype, numberBatches=nbatch)
_ = transform.forward(x, y)

np.max(np.abs(y.get() / y_h - 1.))
```

After I fix the currently incorrect translation of the `axes` argument into `omitDimensions`, passing `axes` should work just the same as scipy for dimensions up to three. I suppose with some juggling more generic batching could be supported as scipy does. Was there a specific use case you had in mind? I'm unsure how common FFTs with super interleaved batching and transform axes are.

**Comment by isuruf** [comment]
Thanks for looking into this. My use-case is in the context of FMM where I have a 2D array and each row has to be transformed, but it's not a 2D FFT.

(Each row can be thought of as a flattened 3D array, making the original array a 4D array, but that doesn't matter)

**Comment by zachjweiner** [comment]
Cool, thanks. It should be quite simple to support the `axes` kwarg for dimensions up to 4, with the caveat that the first axis must be batched for 4D arrays. I'll push a PR soon.
